// <auto-generated />
using System;
using AWPS.IoT.Server.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AWPS.IoT.Server.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDatabase))]
    [Migration("20260314154639_Migration0")]
    partial class Migration0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AWPS.IoT.Server.EFCore.Models.MeasuringDataModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Humidity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Light")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Moisture")
                        .HasColumnType("tinyint");

                    b.Property<short>("Temperature")
                        .HasColumnType("smallint");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Guid");

                    b.ToTable("MeasuringDataSet");
                });
#pragma warning restore 612, 618
        }
    }
}
