<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
    <PackageReference Include="msgpack.light" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\tailwind.css" />
  </ItemGroup>

</Project>