<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MqttResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MqttResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MqttResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MqttResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AWPS.Core.Infrastructure\AWPS.Core.Infrastructure.csproj" />
    <ProjectReference Include="..\AWPS.Deploy\AWPS.Deploy.ServiceDefaults\AWPS.Deploy.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
