//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPS.IoT.MqttInteraction
{
    
    internal partial class MqttResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((MqttResources.manager == null))
                {
                    MqttResources.manager = new System.Resources.ResourceManager("AWPS.IoT.MqttInteraction.MqttResources", typeof(MqttResources).Assembly);
                }
                return MqttResources.manager;
            }
        }
        internal static string GetString(MqttResources.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            ServerUrl = -31503,
            ServerCertificate = 16053,
            Password = 17617,
            UserName = 18015,
        }
    }
}
