<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AWPS.Deploy\AWPS.Deploy.ServiceDefaults\AWPS.Deploy.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AWPS.UI.Web.Client\AWPS.UI.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
  </ItemGroup>

</Project>